### ISSUE TITLE
Rename Repository

### ISSUE THREAD

**Issue by wpank** [w3f/polkadot-validator-setup#119]
The name secure Validator implies that this sets up everything entirely to have a secure set up. This is not necessarily the case - this repo should be used as a template to further make accomodations to ones individual setup. 

I would propose renaming this to `polkadot-validator-template`

**Comment by lamafab** [comment]
The word "secure" made it in there because this repo used to setup sentry nodes and VPN connections, which is no longer relevant, I guess. So I'm giving you an "aye" from my side. It's not really a "template", however.

I propose: `polkadot-validator-setup`
