### ISSUE TITLE
Nominating: Has to be a way to copy and paste multiple validators vs 1 at a time

### ISSUE THREAD

**Issue by btcmacroecon** [w3f/polkadot-validator-setup#143]
This issue arose from different testnet than KSM /Polkadot, but principle is the same. Is there a way to allow for copy and paste of multiple addresses for the validators on the right hand side? Currently looks like only can input 1 at a time, so when you need to change up (in this case testnet) and often, it's a manual deal. For UI, ease of use and user experience perhaps could allow for copy and paste (and show entire address)?

Ability to control color would be beneficial for those with bad eyesite vs the light gray which does not stand out for visually impaired. An option to do so (drop down perhaps) or hover over that points out the option may help some people. 

Also in the nominating process, the little box you check can barely see it due to visual impairment. A box that is colored (or again with option to change up color or boldness) may be helpful for the visually impaired.

**Comment by lamafab** [comment]
HI. I'm not quite sure this is related to this repo? You're probably looking for https://github.com/polkadot-js/apps
