### ISSUE TITLE
add load balancing for public rpc nodes

### ISSUE THREAD

**Issue by brenzi** [w3f/polkadot-validator-setup#148]
Would be great to have auto-deployed load balancing for rpc.
Not sure if all providers offer that

**Comment by lamafab** [comment]
Hello benzi

Load balancing is out the scope of this repo and more related to infrastructure. You could for example use our Ansible scripts to setup all the nodes in a private network, then put a publicly exposed load balancer in front of those. There a couple of (cloud) services that offer that.
