### ISSUE TITLE
Nginx proxy not bring created?

### ISSUE THREAD

**Issue by sashman-jaspin** [w3f/polkadot-validator-setup#153]
Running the ansible setup script on ubuntu 18.  Runs well, except it doesn't look like the nginx config proxing the p2p port (30333) is being set up,  Instead, polkadot is listening on 127.0.0.1.  --listen-addr=/ip4/127.0.0.1/tcp/30333.  I like the idea of proxying through nginx.  Is the documentation not correct or am I missing something in our inventory?

**Comment by lamafab** [comment]
Hi

This behavior is correct: the substrate node will listen on `30333`, where nginx will forward messages to while listing on port `80`. The substrate node announces port `80` to the network [if the proxy is set](https://github.com/w3f/polkadot-validator-setup/blob/master/ansible/roles/polkadot-validator/templates/polkadot.service.j2#L54):

```jinja2
  {% if enable_reverse_proxy is not none and enable_reverse_proxy == 'true' %}
  --public-addr=/ip4/{{ hostvars[inventory_hostname].public_ip.json.ip }}/tcp/{{ proxy_port }} \
  {% endif %}
  ````

So what you have to do is just enable the proxy in the Ansible inventory:

```yaml
enable_reverse_proxy = true
```
