### ISSUE TITLE
Additional Telemetry link

### ISSUE THREAD

**Issue by ilhanu** [w3f/polkadot-validator-setup#59]
Using this tool for deploying and upgrading my kusama nodes, for a specific node I need just one extra input for telemetry-url extra, for matching telemetry-urls I can use the following `polkadot_additional_validator_flags` 

If I have the following:
```
telemetryUrl=wss://mi.private.telemetry.backend/
telemetryUrl=wss://mi.private.telemetry.backend2/
```
It just picks up backend2 and leaves out the first.

**Comment by fgimenez** [comment]
Maybe we could have an array of telemetry endpoints instead of a fixed number of them.

**Comment by truongnhi08** [comment]
> Có lẽ chúng ta có thể có một loạt các điểm cuối đo từ xa thay vì một số lượng cố định.

**Comment by lamafab** [comment]
This is supported now. See sample inventory.
